spring:
  application:
    name: consumer
server:
  port: 8002

  #当前服务/应用的名字
dubbo:
  application:
    name: consumer
  #注册中心的协议和地址
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  #通信规则（通信协议和接口）
  protocol:
    name: dubbo
    port: 20882
  #连接监控中心
  monitor:
    protocol: registry
  #开启包扫描，可替代 @EnableDubbo 注解
  #dubbo.scan.base-packages=com.example.demo.service
